---
- name: "base : set hostnames"
  hostname:
    name: "{{ ec2_tag_Name }}"

- name: "base : build /etc/hosts files"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ ec2_tag_Name }}$'
    line: "{{ ansible_default_ipv4.address }} {{ ec2_tag_Name }}"
    state: present

- name: "base : add apt keys"
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ apt_key_docker }}"
    - "{{ apt_key_kubernetes }}"

- name: "base : add apt repositories"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ apt_repository_docker }}"
    - "{{ apt_repository_kubernetes }}"

- name: "base : install base packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_list:
    - "{{ base_packages }}"
...
