---
### https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Install Docker
  apt:
    name:
      - docker-ce=5:18.09.9~3-0~ubuntu-bionic
      - docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic
    state: present
  notify:
    - restart docker

- name: Template /etc/docker/daemon.json
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Create directory /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify:
    - systemd daemon reload
    - restart docker
...
