---
- name: "docker : install docker packages"
  apt:
    name: "{{ item.package }}={{ item.version }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ docker_packages }}"
  notify:
    - restart docker

- name: "docker : prevent docker packages from being upgraded"
  dpkg_selections:
    name: "{{ item.package }}"
    selection: hold
  with_items:
    - "{{ docker_packages }}"

- name: "docker : template /etc/docker/daemon.json"
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: "docker : create directory /etc/systemd/system/docker.service.d"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  notify:
    - systemd daemon reload
    - restart docker
...
