---
- name: "etcd : template /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf"
  template:
    src: kubelet-etcd-service-manager.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
  notify:
    - systemd daemon reload
    - restart kubelet

- name: "etcd : template /etc/kubernetes/kubeadmcfg.yaml"
  template:
    src: etcd-kubeadmcfg.yaml.j2
    dest: /etc/kubernetes/kubeadmcfg.yaml

- name: "etcd : kubeadm init phase certs etcd-ca"
  shell:
    cmd: kubeadm init phase certs etcd-ca
    creates: /etc/kubernetes/pki/etcd/ca.key
  when: ec2_tag_Name == "etcd-a"

- name: "etcd : fetch certs from etcd-a"
  fetch:
    src: /etc/kubernetes/pki/etcd/{{ item }}
    dest: /tmp/kubernetes-cluster-etcd/
    flat: yes
  with_items:
    - ca.crt
    - ca.key
  when: ec2_tag_Name == "etcd-a"

- name: "etcd : copy certs to etcd hosts"
  copy:
    src: /tmp/kubernetes-cluster-etcd/
    dest: /etc/kubernetes/pki/etcd/
  when: ec2_tag_Name != "etcd-a"

- name: "etcd : remove local directory /tmp/kubernetes-cluster-etcd/"
  local_action:
    module: file
    path: /tmp/kubernetes-cluster-etcd/
    state: absent
  become: no
  run_once: true

- name: "etcd : set /etc/kubernetes/pki/etcd/ca.key file permissions"
  file:
    path: /etc/kubernetes/pki/etcd/ca.key
    mode: '0600'
  when: ec2_tag_Name != "etcd-a"

- name: "etcd : kubeadm init phase certs ...."
  shell:
    cmd: "{{ item }}"
  with_items:
    - "kubeadm init phase certs etcd-server --config=/etc/kubernetes/kubeadmcfg.yaml"
    - "kubeadm init phase certs etcd-peer --config=/etc/kubernetes/kubeadmcfg.yaml"
    - "kubeadm init phase certs etcd-healthcheck-client --config=/etc/kubernetes/kubeadmcfg.yaml"
    - "kubeadm init phase certs apiserver-etcd-client --config=/etc/kubernetes/kubeadmcfg.yaml"

- name: "etcd : remove /etc/kubernetes/pki/etcd/ca.key"
  file:
    path: /etc/kubernetes/pki/etcd/ca.key
    state: absent
  when: ec2_tag_Name != "etcd-a"

- name: "etcd : kubeadm init phase etcd local"
  shell:
    cmd: kubeadm init phase etcd local --config=/etc/kubernetes/kubeadmcfg.yaml
...
