---
- name: Template /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
  template:
    src: kubelet-etcd-service-manager.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
  notify:
    - systemd daemon reload
    - restart kubelet

- name: Template /tmp/etcd-kubeadmcfg.yaml
  template:
    src: etcd-kubeadmcfg.yaml.j2
    dest: /tmp/kubeadmcfg.yaml

- name: kubeadm init phase certs etcd-ca
  shell:
    cmd: kubeadm init phase certs etcd-ca
    creates: /etc/kubernetes/pki/etcd/ca.key
  when: ec2_tag_Name == "etcd-a"
...
