---
- name: "include base.yml"
  include_tasks:
    file: base.yml
    apply:
      tags:
        - base
  tags:
    - base

- name: "include docker.yml"
  include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  tags:
    - docker

- name: "include kubernetes.yml"
  include_tasks:
    file: kubernetes.yml
    apply:
      tags:
        - kubernetes
  tags:
    - kubernetes

- name: Include etcd
  include_tasks: etcd.yml
  when: inventory_hostname in groups['tag_Type_etcd']

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Include control_plane
  include_tasks: control_plane.yml
  # when: inventory_hostname in groups['tag_Type_master']

- name: Include worker
  include_tasks: worker.yml
...
