---
- name: Include base tasks
  include_tasks: base.yml

- name: Include docker
  include_tasks: docker.yml

### to be addded to a specific file
- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Prevent Kubernetes packages of being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_list:
    - kubelet
    - kubeadm
    - kubectl

- name: Include etcd
  include_tasks: etcd.yml
  when: inventory_hostname in groups['tag_Type_etcd']

- name: Include control_plane
  include_tasks: control_plane.yml
  when: inventory_hostname in groups['tag_Type_master']
...
