---
- name: "include base.yml"
  include_tasks:
    file: base.yml
    apply:
      tags:
        - base
  tags:
    - base

- name: "include docker.yml"
  include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  tags:
    - docker

- name: "include kubernetes.yml"
  include_tasks:
    file: kubernetes.yml
    apply:
      tags:
        - kubernetes
  tags:
    - kubernetes

- name: "include etcd.yml"
  include_tasks:
    file: etcd.yml
    apply:
      tags:
        - etcd
  tags:
    - etcd
  when: ec2_tag_Type == "etcd"

- name: "force all notified handlers to run at this point"
  meta: flush_handlers

- name: "include control_plane.yml"
  include_tasks:
    file: control_plane.yml
    apply:
      tags:
        - control_plane
  tags:
    - control_plane

- name: "include worker.yml"
  include_tasks:
    file: worker.yml
    apply:
      tags:
        - worker
  tags:
    - worker
...
