---
- name: "worker : kubeadm token create"
  shell:
    cmd: kubeadm token create --print-join-command --ttl 30m
  register: token_create
  when: ec2_tag_Name == "master-a"

- name: "worker : kubeadm join"
  shell:
    cmd: "{{ hostvars['master_a']['token_create']['stdout'] }}"
    creates: /etc/kubernetes/kubelet.conf
  when: ec2_tag_Type == "worker"
...
