---
- name: systemd daemon reload
  systemd:
    daemon_reload: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted

...
